### ISSUE TITLE
invalid option: --manifestdir from Puppet

### ISSUE THREAD

**Issue by pliguori** [tayzlor/vagrant-puppet-mesosphere#12]
when calling vagrant up, on each VM I'm getting the following error, but I cannot find anywhere this --manifestdir option passed to Puppet

==> master1: Mounting shared folders...
    master1: /vagrant => /Users/pietro/devel/mesos/cluster/vagrant-puppet-mesosphere/cluster
    master1: /tmp/vagrant-puppet/modules-cdf1c406d701e17b01eebba7fab5df3f => /Users/pietro/devel/mesos/cluster/vagrant-puppet-mesosphere/modules
    master1: /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513 => /Users/pietro/devel/mesos/cluster/vagrant-puppet-mesosphere/cluster/manifests
==> master1: Running provisioner: puppet...
==> master1: Running Puppet with mesos-master.pp...
==> master1: stdin: is not a tty
==> master1: Error: Could not parse application options: invalid option: --manifestdir
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by abstratt** [comment]
Same here.

**Comment by tayzlor** [comment]
Should hopefully be fixed in the above, try pulling master and trying again. Locks the base box to version 1.0.0 of puppetlabs/ubuntu-14.04-64-puppet

**Comment by abstratt** [comment]
That worked for me, thanks!
