### ISSUE TITLE
Add a license to the repo

### ISSUE THREAD

**Issue by mbrukman** [tayzlor/vagrant-puppet-mesosphere#6]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms you're providing this code?

Thanks!

**Comment by tayzlor** [comment]
Fixed in https://github.com/tayzlor/vagrant-puppet-mesosphere/commit/caaf9fb06a57604bf0873b54153cdb4c2e26b0a7

**Comment by mbrukman** [comment]
Thanks, @tayzlor!
