### ISSUE TITLE
Problem with location of classes

### ISSUE THREAD

**Issue by granthbr** [tayzlor/vagrant-puppet-mesosphere#7]
I've been experimenting with the stand-alone and the clustered version for Virtualbox. I've been running into issues with class location (see error below this description). Some of the suggestions on the web say it is related to permissions issues on the image. Has anyone encountered similar issues?

==> default: Error: Could not find class zookeeper for mesos on node mesos
==> default: Error: Could not find class zookeeper for mesos on node mesos

**Comment by wallies** [comment]
@granthbr you may have to run 
```
git submodules update --init
```
As there is a .gitmodules folder which will pull in the zookeeper and any other community puppet modules

**Comment by granthbr** [comment]
Thanks @wallies I did miss that. That worked perfectly!
